### ISSUE TITLE
NOt dowloading anymore

### ISSUE THREAD

**Issue by gilgam** [mattetti/pluzzdl#2]
Since 30 april the script does not download le video anymore. 

Here is the error message  

```
[unknown@nidavellir-localdomain pluzzdl-master_last]$ ./pluzzdl.sh -vb http://pluzz.francetv.fr/videos/silence_ca_pousse_.html
[DEBUG   ]  main.py             pluzzdl 0.9.4 avec Python 2.7.5 (x86_64)
[DEBUG   ]  main.py             OS : Linux #1 SMP Fri Dec 13 22:33:23 UTC 2013
[DEBUG   ]  Navigateur.py       GET http://pluzz.francetv.fr/videos/silence_ca_pousse_.html
[DEBUG   ]  PluzzDL.py          ID de l'émission : 101150030
[DEBUG   ]  Navigateur.py       GET http://www.pluzz.fr/appftv/webservices/video/getInfosOeuvre.php?mode=zeri&id-diffusion=101150030
Traceback (most recent call last):
  File "src/main.py", line 94, in <module>
    progressFnct = progressFnct )
  File "/home/unknown/bin/pluzzdl-master_last/src/PluzzDL.py", line 80, in __init__
    self.parseInfos( pageInfos )
  File "/home/unknown/bin/pluzzdl-master_last/src/PluzzDL.py", line 146, in parseInfos
    raise PluzzDLException( "Impossible de parser le fichier XML de l'émission" )
PluzzDL.PluzzDLException: Impossible de parser le fichier XML de l'émission
```

Thanks for helping.

**Comment by ziirish** [comment]
Have a look at my PR #3
