### ISSUE TITLE
dl failed on http://pluzz.francetv.fr/videos/c_dans_lair.html of Jan 12th 2015

### ISSUE THREAD

**Issue by fbone** [mattetti/pluzzdl#4]
First thanks for the great job on pluzzdl!
I use it everyday and it works very well.
However since Jan 12th 2015 it fails on c_dans_lair TV show on france 5.
Did pluzz change anything on their website?
Please find below debug log:

$ pluzzdl -v  http://pluzz.francetv.fr/videos/c_dans_lair.html
[DEBUG   ]  main.py             pluzzdl 0.9.4 avec Python 2.7.6 (i686)
[DEBUG   ]  main.py             OS : Linux #72-Ubuntu SMP Mon Dec 8 19:35:44 UTC 2014
[DEBUG   ]  Navigateur.py       GET http://pluzz.francetv.fr/videos/c_dans_lair.html
[DEBUG   ]  PluzzDL.py          ID de l'émission : 115500690
[DEBUG   ]  Navigateur.py       GET http://www.pluzz.fr/appftv/webservices/video/getInfosOeuvre.php?mode=zeri&id-diffusion=115500690
[DEBUG   ]  PluzzDL.py          m3u8URL file missing, we will try to guess it
[DEBUG   ]  PluzzDL.py          URL m3u8 : http://ftvodhdsecz-f.akamaihd.net/i/streaming-adaptatif/2015/S03/J1/115500690-20150112-,398,k.mp4.csmil/index_2_av.m3u8
[DEBUG   ]  PluzzDL.py          URL manifest : http://ftvodhdsecz-f.akamaihd.net/z/streaming-adaptatif/2015/S03/J1/115500690-20150112-,398,k.mp4.csmil/manifest.f4m
[DEBUG   ]  PluzzDL.py          Lien RTMP : None
[DEBUG   ]  PluzzDL.py          Lien MMS : None
[DEBUG   ]  PluzzDL.py          Utilisation de DRM : non
[DEBUG   ]  Historique.py       Historique chargé
[DEBUG   ]  Navigateur.py       GET http://ftvodhdsecz-f.akamaihd.net/i/streaming-adaptatif/2015/S03/J1/115500690-20150112-,398,k.mp4.csmil/index_2_av.m3u8
[DEBUG   ]  Navigateur.py       Not Found
Traceback (most recent call last):
  File "/usr/share/pluzzdl/main.py", line 94, in <module>
    progressFnct = progressFnct )
  File "/usr/share/pluzzdl/PluzzDL.py", line 113, in **init**
    downloader.telecharger()
  File "/usr/share/pluzzdl/PluzzDL.py", line 270, in telecharger
    self.m3u8 = self.navigateur.getFichier( self.m3u8URL )
  File "/usr/share/pluzzdl/Navigateur.py", line 59, in getFichier
    page = self.urlOpener.open( requete, timeout = self.timeOut )
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
[DEBUG   ]  Historique.py       Historique sauvé

--> KO

By the way it is still working on old replay Jan 9th 2015 of c_dans_lair.html:

$ pluzzdl -vv http://pluzz.francetv.fr/videos/c_dans_lair_,114197704.html
[DEBUG   ]  main.py             pluzzdl 0.9.4 avec Python 2.7.6 (i686)
[DEBUG   ]  main.py             OS : Linux #72-Ubuntu SMP Mon Dec 8 19:35:44 UTC 2014
[DEBUG   ]  Navigateur.py       GET http://pluzz.francetv.fr/videos/c_dans_lair_,114197704.html
[DEBUG   ]  PluzzDL.py          ID de l'émission : 114197704
[DEBUG   ]  Navigateur.py       GET http://www.pluzz.fr/appftv/webservices/video/getInfosOeuvre.php?mode=zeri&id-diffusion=114197704
[DEBUG   ]  PluzzDL.py          m3u8URL file missing, we will try to guess it
[DEBUG   ]  PluzzDL.py          URL m3u8 : http://ftvodhdsecz-f.akamaihd.net/i/streaming-adaptatif/2015/S02/J5/114197704-20150109-,398,632,934,k.mp4.csmil/index_2_av.m3u8
[DEBUG   ]  PluzzDL.py          URL manifest : http://ftvodhdsecz-f.akamaihd.net/z/streaming-adaptatif/2015/S02/J5/114197704-20150109-,398,632,934,k.mp4.csmil/manifest.f4m
[DEBUG   ]  PluzzDL.py          Lien RTMP : None
[DEBUG   ]  PluzzDL.py          Lien MMS : None
[DEBUG   ]  PluzzDL.py          Utilisation de DRM : non
[DEBUG   ]  Historique.py       Historique chargé
[DEBUG   ]  Navigateur.py       GET http://ftvodhdsecz-f.akamaihd.net/i/streaming-adaptatif/2015/S02/J5/114197704-20150109-,398,632,934,k.mp4.csmil/index_2_av.m3u8
[INFO    ]  PluzzDL.py          Impossible de reprendre le téléchargement de la vidéo, le fichier ./c_dans_lair_2015-01-09_17-46.ts n'existe pas
[DEBUG   ]  PluzzDL.py          Nombre de fragments : 412
[INFO    ]  PluzzDL.py          Début du téléchargement des fragments
[DEBUG   ]  Navigateur.py       GET http://ftvodhdsecz-f.akamaihd.net/i/streaming-adaptatif/2015/S02/J5/114197704-20150109-,398,632,934,k.mp4.csmil/segment1_2_av.ts
[DEBUG   ]  Navigateur.py       GET http://ftvodhdsecz-f.akamaihd.net/i/streaming-adaptatif/2015/S02/J5/114197704-20150109-,398,632,934,k.mp4.csmil/segment2_2_av.ts
[DEBUG   ]  Navigateur.py       GET http://ftvodhdsecz-f.akamaihd.net/i/streaming-adaptatif/2015/S02/J5/114197704-20150109-,398,632,934,k.mp4.csmil/segment3_2_av.ts
[DEBUG   ]  Navigateur.py       GET http://ftvodhdsecz-f.akamaihd.net/i/streaming-adaptatif/2015/S02/J5/114197704-20150109-,398,632,934,k.mp4.csmil/segment4_2_av.ts
[DEBUG   ]  Navigateur.py       GET http://ftvodhdsecz-f.akamaihd.net/i/streaming-adaptatif/2015/S02/J5/114197704-20150109-,398,632,934,k.mp4.csmil/segment5_2_av.ts

--> OK

Best regards

Fred

**Comment by mattetti** [comment]
Sorry, I'm not using this script anymore. I'm now using a mix of https://github.com/mattetti/m3u8Grabber and some JS parsers, sorry :(
